# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: 
date_format: "ordinal"
title: BNG 技术博客
subtitle: 
description: 
keywords: 
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
default_author: Bell Net Group
organization: Bell Net Group
organization_url: github.com/elcbng
github_username: elcbng

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页
  -
    href: /categories/
    label: 归档
  -
    href: /wiki/
    label: 维基
  -
    href: /note/
    label: 笔记
  -
    href: /about/
    label: 关于
  -
    href: /open-source/
    label: 项目

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: <!--more-->
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-paginate
    - jekyll-github-metadata
    - rouge
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    note:
        output: true
        permalink: /note/:path/

repository: elcbng/elcbng.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: elcbng
    repo: elcbng.github.io
    clientID: a420ded1ae6a7a2b61a6
    clientSecret: 3477f9f6576438b34d93e3eebe1a504e8085a7b4

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10
